version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_OWN_KEY=${OWN_API_KEY}
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - VLLM_API_BASE=${VLLM_API_BASE}
      - OWN_API_KEY=${OWN_API_KEY}
  vllm:
    image: vllm/vllm-openai:latest
    command: ["--model", "gpt-oss-120b"]
    ports:
      - "8001:8000"
